apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-03-07T18:34:53Z","generation":1,"labels":{"run":"apiexpressnodb"},"name":"apiexpressnodb","namespace":"default","resourceVersion":"2662906","selfLink":"/apis/apps/v1/namespaces/default/deployments/apiexpressnodb","uid":"2c685f92-0fac-49fb-9592-af03cde02398"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"apiexpressnodb"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"apiexpressnodb"}},"spec":{"containers":[{"image":"patvin80/apiexpressnodb:1251c2b-dirty","imagePullPolicy":"IfNotPresent","name":"apiexpressnodb","ports":[{"containerPort":3000}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-03-07T18:34:54Z","lastUpdateTime":"2021-03-07T18:34:54Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-03-07T18:34:53Z","lastUpdateTime":"2021-03-07T18:34:54Z","message":"ReplicaSet \"apiexpressnodb-7d757756bb\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2021-03-07T18:34:53Z"
  generation: 2
  labels:
    run: apiexpressnodb
  name: apiexpressnodb
  namespace: default
  resourceVersion: "2665670"
  selfLink: /apis/apps/v1/namespaces/default/deployments/apiexpressnodb
  uid: 2c685f92-0fac-49fb-9592-af03cde02398
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: apiexpressnodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: apiexpressnodb
    spec:
      containers:
      - image: patvin80/apiexpressnodb:1251c2b-dirty
        imagePullPolicy: IfNotPresent
        name: apiexpressnodb
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-07T18:34:54Z"
    lastUpdateTime: "2021-03-07T18:34:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-03-07T18:34:53Z"
    lastUpdateTime: "2021-03-07T19:01:32Z"
    message: ReplicaSet "apiexpressnodb-7456998fc8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
